### ISSUE TITLE
Cockpit is messed up 

### ISSUE THREAD

**Issue by saasuliman** [SoftwareAG/cumulocity-3d-model-viewer-widget#1]
The cumulocity cockpit version is very old & there's issues with it after deploying - for example the groups and devices on left navigation bar when clicked on them are not opening! the data-points-table is loading forever and doesn't show any. 
These the only two I noticed and I'm sure there's more, I believe the cockpit source has some issues

**Comment by YashPShah-swag** [comment]
Please try the new plugin version, if issue persists raise an issue in plugin repository. [Plugin](https://github.com/SoftwareAG/cumulocity-3d-model-viewer-widget-plugin)
